### ISSUE TITLE
请教

### ISSUE THREAD

**Issue by ibufu** [Lobos/react-language#1]
```js
if (!isShow) {
      return DOM.noscript();
}
```
这里和 return null有什么区别呢？

**Comment by Lobos** [comment]
react是不能return null的，一定要return一个element。<noscript />不受css样式影响。

**Comment by ibufu** [comment]
不是吧，这里改成return null，是可以编译成<- ->这种的。

**Comment by Lobos** [comment]
我记得是会报一个错的，难道是react版本的原因？
