### ISSUE TITLE
请教下这里 if else 判断逻辑的区别

### ISSUE THREAD

**Issue by byr-gdp** [Lobos/react-language#2]
https://github.com/Lobos/react-language/blob/6d0d952620eac8545fc07e6f40eb7ef1352a8d2e/src/index.js#L78

直接返回 `createElement(tag, {}, children);` 有什么问题吗？

**Comment by Lobos** [comment]
只有一个ReactElement的时候，直接返回原对象。因为当时写这个的时候，还没有Fragment，所以当children是多个React组件的时候，用createElement创建一个元素做容器，但是这样不太好，会破坏dom结构。现在的话，可以直接用Fragment 就好了。

**Comment by byr-gdp** [comment]
多谢回复。

就是说 `isValidElement` 只能判断 single Element，如果 Component 返回多个 Element，会判别为 false 吧

**Comment by Lobos** [comment]
对的，其他的数组，字符串，null等都会判断为false
